Ground Booking/ground_book/general/urls.py
from django.conf.urls import url
from . import views

app_name = 'general'

urlpatterns = [
    url(r'^gallery/$', views.GalleryView.as_view(), name='gallery'),
    url(r'^events/$', views.AvailableEvents.as_view(), name='available_events'),
    url(r"^events/in/(?P<slug>[-\w]+)/$", views.SingleEvent.as_view(), name="single"),
    url(r'^about/$', views.About.as_view(), name='about'),
    url(r'^contact/$', views.Contact.as_view(), name='contact'),
]

Ground Booking/ground_book/ground_book/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.Home.as_view(), name='homepage'),
    url(r'^general/', include('general.urls', namespace='general')),
    url(r'^bookings/', include('slot_book.urls', namespace='booking')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ground Booking/ground_book/slot_book/urls.py
from django.conf.urls import url
from . import views


app_name = 'booking'

urlpatterns = [
    url(r'^$', views.BookingInfoView.as_view(), name='booking_info'),
    url(r'^checkout/$', views.Checkout.as_view(), name='checkout'),
    url(r'^booked/$', views.Booked.as_view(), name='booked'),
]

Ground Booking/ground_book/general/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

# Create your models here.


def get_image_filename(instance, filename):
    title = instance.title
    slug = slugify(title)
    return "media/general/images/event_images/%s-%s" % (slug, filename)


class Gallery(models.Model):
    title = models.CharField(max_length=150)
    image1 = models.ImageField(upload_to=get_image_filename, verbose_name='Image1', blank=True)
    image2 = models.ImageField(upload_to=get_image_filename, verbose_name='Image2', blank=True)
    image3 = models.ImageField(upload_to=get_image_filename, verbose_name='Image3', blank=True)
    image4 = models.ImageField(upload_to=get_image_filename, verbose_name='Image4', blank=True)
    image5 = models.ImageField(upload_to=get_image_filename, verbose_name='Image5', blank=True)
    image6 = models.ImageField(upload_to=get_image_filename, verbose_name='Image6', blank=True)
    image7 = models.ImageField(upload_to=get_image_filename, verbose_name='Image7', blank=True)
    image8 = models.ImageField(upload_to=get_image_filename, verbose_name='Image8', blank=True)
    image9 = models.ImageField(upload_to=get_image_filename, verbose_name='Image9', blank=True)
    image10 = models.ImageField(upload_to=get_image_filename, verbose_name='Image10', blank=True)

    def __str__(self):
        return self.title


class AvailEvents(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=550)
    slug = models.SlugField(allow_unicode=True, unique=True)
    image = models.ImageField(upload_to=get_image_filename, verbose_name='Thumbnail', blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('general:single', kwargs={'slug': self.slug})

Ground Booking/ground_book/slot_book/models.py
from django.db import models
from datetime import datetime, date
from django.urls import reverse


class BookingDetails(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    team_name = models.CharField(max_length=50)
    contact = models.CharField(max_length=10)
    slot_date = models.DateField('Slot Date(mm/dd/yyyy)', auto_now_add=False, auto_now=False)
    booked_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    slot_choices = (
                    ('1:6am-10am', '6am-10am'),
                    ('2:10am-2pm', '10am-2pm'),
                    ('3:2pm-5pm', '2pm-5pm'),
                    )
    slot_num = models.CharField(max_length=30, choices=slot_choices)

    def __str__(self):
        return self.name

    def save(self, *args):
        super().save(*args)

    def get_absolute_url(self):
        return reverse('booking:checkout')

Ground Booking/ground_book/general/forms.py
from django import forms

Ground Booking/ground_book/slot_book/forms.py
from django import forms
from .models import BookingDetails


class BookingForm(forms.ModelForm):
    class Meta:
        fields = ('name', 'email', 'team_name', 'contact', 'slot_date', 'slot_num')
        model = BookingDetails

Ground Booking/ground_book/general/views.py
from django.views.generic import (TemplateView, DetailView)
from .models import Gallery, AvailEvents
from django.shortcuts import render
# Create your views here.


class GalleryView(TemplateView):
    model = Gallery
    template_name = 'general/gallery.html'

    def get(self, request):
        gallery = Gallery.objects.all()
        context = {'gallery': gallery}
        return render(request, self.template_name, context)


class AvailableEvents(TemplateView):
    template_name = 'general/available_events.html'
    model = AvailEvents

    def get(self, request):
        events = AvailEvents.objects.all()
        context = {'events': events}
        return render(request, self.template_name, context)


class SingleEvent(DetailView):
    model = AvailEvents
    template_name = 'general/single_event.html'


class About(TemplateView):
    template_name = 'general/about.html'


class Contact(TemplateView):
    template_name = 'general/contact.html'

Ground Booking/ground_book/ground_book/views.py
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = 'homepage.html'

Ground Booking/ground_book/slot_book/views.py
from django.shortcuts import render
from django.views.generic import (CreateView,
                                  TemplateView,
                                  ListView)
from .models import BookingDetails
import datetime


class BookingInfoView(CreateView):
    fields = ('name', 'email', 'team_name', 'contact', 'slot_date', 'slot_num')
    model = BookingDetails
    # template_name = 'slot_book/bookingdetails_form.html'

    def form_valid(self, form):
        return super().form_valid(form)


class Booked(ListView):
    model = BookingDetails
    template_name = 'slot_book/booked_slots.html'

    def get(self, request):
        today = datetime.datetime.now()
        slots = BookingDetails.objects.filter(slot_date__gte=today)
        context = {'slots': slots}
        return render(request, self.template_name, context)


class Checkout(TemplateView):
    template_name = 'slot_book/checkout.html'

Ground Booking/ground_book/general/templates/general/about.html
{% extends 'base.html' %}
{% block title %}About Us{% endblock %}
{% block content %}
<div class="container fluid">
  <h1 class="heading">We encourage Sporting</h1>
  <hr>
  <div class="row">
  <div class="col-md-6">
    <h1>About us</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  <div class="col-md-6">
    <h2>Our mission</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <h2>Our Promise</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
</div>
</div>
<style>
  .heading{
    margin-left: 25%;
    }
</style>
{% endblock %}

Ground Booking/ground_book/general/templates/general/available_events.html
{% extends 'base.html' %}
{% block title %}Events{% endblock %}
{% block content %}
<h1>This is Event page</h1>
<style>
  img{
    margin-top: 20px;
    margin-bottom: 20px;

  }
</style>
{% for event in events %}
<div class="container marketing">
  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">{{ event.title}}</h2>
      <p class="lead">{{ event.description }}</p>
      <p><a class="btn btn-secondary" href="{% url 'general:single' slug=event.slug %}" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-5">
      <img src="{{ event.image.url }}" alt="" class="img-fluid img-thumbnail" style="width:400px;height:400px;">
     </div>
  </div>
  </div>
  {% endfor %}
{% endblock %}

Ground Booking/ground_book/general/templates/general/contact.html
{% extends 'base.html' %}
{% block title %}Contact Us{% endblock %}
{% block content %}

<div class="container">
  <h1 style="text-align:center; transform: 2;">Reach Out</h1>
  <div class="row">
    <div class="col-md-8">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3808.4264160310986!2d78.33514841512749!3d17.343202508642197!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bcb9575f5916ff3%3A0x1abb43806c7abca!2sSanjeevani%20Cricket%20Arena!5e0!3m2!1sen!2sin!4v1580760750724!5m2!1sen!2sin" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
    </div>
    <div class="col-md-4">
      <h3>Find Us</h3>
      <hr>
      <h4>Address</h4>
      <p>Sanjeevani Cricket Arena <br>
         view tennis academy, <br>
         Aziznagar Village Rd, <br>
         beside lake, <br>
         Hyderabad, Telangana <br>
         500075</p>
      <h4>Email</h4>
      <p>Abcd@gmail.com</p>
      <h4>Mobile</h4>
      <p>1234567890</p>
    </div>
  </div>

</div>
{% endblock %}

Ground Booking/ground_book/general/templates/general/single_event.html
{% extends 'base.html' %}
{% block title %}{{availevents.title}}{% endblock %}
{% block content %}
<div class="container fluid">
<h1>{{availevents.title}}</h1>
<h5>{{availevents.description}}</h5>
<p><a class="btn btn-secondary" href="{% url 'booking:booked' %}" role="button">Book Now &raquo;</a></p>
</div>
{% endblock %}

Ground Booking/ground_book/slot_book/templates/slot_book/booked_slots.html
{% extends 'base.html' %}
{% block content %}
<div class="container"><br>
  <h3>List of already booked slots</h3> <br>
  <table class="table table-hover">
    <th>Booked By</th>
    <th>Team Name</th>
    <th>Booking For Date</th>
    <th>Slot</th>
  {% for slot in slots %}
  <tr>
    <td>{{slot.name}}</td>
    <td>{{slot.team_name}}</td>
    <td>{{slot.slot_date}}</td>
    <td>{{slot.slot_num}}</td>
  </tr>
  {% endfor %}
  </table>

  <a href="{% url 'booking:booking_info' %}" class="btn btn-primary">Go To Booking Page</a>
</div>
{% endblock %}

Ground Booking/ground_book/slot_book/templates/slot_book/bookingdetails_form.html
{% extends 'base.html' %}
{% load static %}

{% load bootstrap3 %}

{% block title %}Booking{% endblock %}
{% block css_link %}
<link href="{% static 'slot_book/js/jquery-ui-1.12.1/jquery-ui.min.css' %}" rel="stylesheet">
<link href="{% static 'slot_book/js/jquery-ui-1.12.1/jquery-ui.structure.min.css' %}" rel="stylesheet">
<link href="{% static 'slot_book/js/jquery-ui-1.12.1/jquery-ui.theme.min.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container fluid">
<h1>This is booking page</h1>
<form method="POST" action="{% url 'booking:booking_info' %}" >
	{% csrf_token %}
	<!-- {{ form.as_p }} -->
  {% bootstrap_form form %}
	<input type="submit" value="Book Now" class="btn btn-primary btn-large">
</form>
</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="{% static 'slot_book/js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'slot_book/js/jquery-ui-1.12.1/jquery-ui.js' %}"></script>
<script src="{% static 'slot_book/js/custom.js' %}"></script>
{% endblock %}

Ground Booking/ground_book/slot_book/templates/slot_book/checkout.html
{% extends 'base.html' %}
{% block title %}Checkout{% endblock %}
{% block content %}
<h1>This is checkout page</h1>
{% endblock %}

Ground Booking/ground_book/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    {% block title %}
    {% endblock %}
    </title>
    {% block css_link %}
    {% endblock %}
    <!-- bootstrap link -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


</head>
<body>
  <!-- <div class="container"> -->
      <nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color: #e1eff5;">
        <a class="navbar-brand" href="{% url 'homepage' %}">
          <img src="{% static 'general/images/sanjeevani crest.png' %}" width="30" height="30" alt="">
        </a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'general:available_events' %}">Events</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'general:gallery' %}">Gallery</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'booking:booked' %}">Book Now</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'general:about' %}">About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'general:contact' %}">Contact Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
        </ul>
      </nav>
  <!-- </div> -->

{% block content %}

{% endblock %}


<!-- Footer -->
<footer class="page-footer font-small unique-color-dark">

  <div style="background-color: #e1eff5;">
    <div class="container">

      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center">

        <!-- Grid column -->
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
          <h6 class="mb-0">Get connected with us on social networks!</h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-6 col-lg-7 text-center text-md-right">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f white-text mr-4"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter white-text mr-4"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g white-text mr-4"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in white-text mr-4"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram white-text"> </i>
          </a>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->

    </div>
  </div>

  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">

    <!-- Grid row -->
    <div class="row mt-3">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold">Company name</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet,
          consectetur
          adipisicing elit.</p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Products</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a href="#!">MDBootstrap</a>
        </p>
        <p>
          <a href="#!">MDWordPress</a>
        </p>
        <p>
          <a href="#!">BrandFlow</a>
        </p>
        <p>
          <a href="#!">Bootstrap Angular</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Useful links</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a href="#!">Your Account</a>
        </p>
        <p>
          <a href="#!">Become an Affiliate</a>
        </p>
        <p>
          <a href="#!">Shipping Rates</a>
        </p>
        <p>
          <a href="#!">Help</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Contact</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
        <p>
          <i class="fas fa-envelope mr-3"></i> info@example.com</p>
        <p>
          <i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
        <p>
          <i class="fas fa-print mr-3"></i> + 01 234 567 89</p>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->


</body>
</html>

Ground Booking/ground_book/templates/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active" data-interval="10000">
      <img src="{% static 'general/images/_MG_3693.jpg' %}" style="width:300px;height:600px;" class=" c_img d-block mh-25 w-100 img-fluid" alt="...">
      <div class="carousel-caption d-none d-md-block text-left">
        <h5>First slide label</h5>
        <p "c_par">Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
      </div>
    </div>
    <div class="carousel-item" data-interval="10000">
      <img src="{% static 'general/images/_MG_3730.jpg' %}" style="width:300px;height:600px;" class="c_img d-block mh-25 w-100" alt="...">
      <div class="carousel-caption d-none d-md-block text-left">
        <h5>Second slide label</h5>
        <p "c_par">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
      </div>
    </div>
    <div class="carousel-item" data-interval="10000">
      <img src="{% static 'general/images/_MG_3732.jpg' %}" style="width:300px;height:600px;" class="c_img  d-block mh-25 w-100" alt="...">
      <div class="carousel-caption d-none d-md-block text-left">
        <h5>Third slide label</h5>
        <p class="c_par">Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container marketing">
   <!-- Three columns of text below the carousel -->
   <div class="row">
     <div class="col-lg-4">
       <img src="{% static 'general/images/events.jpg' %}" alt="" class="rounded-circle" style="width:250px;height:250px; margin-top: 20px; margin-left: 50px;">
       <h2>Events</h2>
       <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
       <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
     </div><!-- /.col-lg-4 -->
     <div class="col-lg-4">
       <img src="{% static 'general/images/coaching.jpg' %}" alt="" class="rounded-circle" style="width:250px;height:250px; margin-top: 20px; margin-left: 50px;">
       <h2>Coaching</h2>
       <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
       <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
     </div><!-- /.col-lg-4 -->
     <div class="col-lg-4">
       <img src="{% static 'general/images/gallery.jpg' %}" alt="" class="rounded-circle" style="width:250px;height:250px; margin-top: 20px; margin-left: 50px;">
       <h2>Gallery</h2>
       <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
       <p><a class="btn btn-secondary" href="{% url 'general:gallery' %}" role="button">View details &raquo;</a></p>
     </div><!-- /.col-lg-4 -->
   </div><!-- /.row -->


   <!-- START THE FEATURETTES -->

   <hr class="featurette-divider">

   <div class="row featurette">
     <div class="col-md-7">
       <h2 class="featurette-heading">Why Us ? <span class="text-muted">Sports for all</span></h2>
       <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
     </div>
     <div class="col-md-5">
       <img src="{% static 'general/images/whyus.jpg' %}" alt="" style="width:500px;height:500px;">
      </div>
   </div>

   <hr class="featurette-divider">

   <div class="row featurette">
     <div class="col-md-7 order-md-2">
       <h2 class="featurette-heading">Infrastructure and Environment. <span class="text-muted">Peaceful and competetive</span></h2>
       <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
     </div>
     <div class="col-md-5 order-md-1">
       <img src="{% static 'general/images/infra.jpg' %}" alt="" style="width:450px;height:450px;">
     </div>
   </div>

   <hr class="featurette-divider">

   <div class="row featurette">
     <div class="col-md-7">
       <h2 class="featurette-heading">Future Plans <span class="text-muted">Coming Soon</span></h2>
       <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
     </div>
     <div class="col-md-5">
       <img src="{% static 'general/images/coming.jpg' %}" alt="" style="width:500px;height:500px;">
     </div>
   </div>

   <hr class="featurette-divider">

   <!-- /END THE FEATURETTES -->

 </div><!-- /.container -->
{% endblock %}